In [ ]:
import numpy as np

class RidgeRegressionFeatureSpace:
    def __init__(self, lambda_reg=2):
        self.lambda_reg = lambda_reg
        self.w = None
    
    def phi(self, x):
        x1, x2 = x
        c = np.sqrt(2)
        return np.array([
            1,          
            x1**2,      
            x2**2,      
            c * x1,     
            c * x2,     
            c * x1 * x2  
        ])
    
    def fit(self, X, y):
        n_samples = len(X)
        # Create design matrix Φ by applying phi to each input
        Phi = np.array([self.phi(x) for x in X])
        # Compute ΦᵀΦ
        PhiT_Phi = Phi.T @ Phi
        # Add regularization term nλI
        n_features = Phi.shape[1]
        reg_term = n_samples * self.lambda_reg * np.eye(n_features)
        # Solve for w* = (ΦᵀΦ + nλI)⁻¹Φᵀy
        self.w = np.linalg.solve(PhiT_Phi + reg_term, Phi.T @ y)
        return self

    def predict(self, X):
        if self.w is None:
            raise ValueError("Model must be fitted before making predictions")
        return np.array([self.phi(x) @ self.w for x in X])

# Test the implementation
def main():
    # Training data
    X = np.array([
        [0, 2],
        [1, 0],
        [0, -2],
        [-1, 0],
        [0, 0]
    ])
    y = np.array([1, 1, 1, 1, -1])
    # Create and fit model
    model = RidgeRegressionFeatureSpace(lambda_reg=2)
    model.fit(X, y)
    # Print weight
    feature_names = ['bias', 'x1²', 'x2²', '√2x1', '√2x2', '√2x1x2']
    print("Optimal weights w*:")
    for name, weight in zip(feature_names, model.w):
        print(f"{name:8}: {weight:0.4f}")
    # Make predictions
    y_pred = model.predict(X)
    print("\nPredictions vs Actual:")
    for i, (pred, actual) in enumerate(zip(y_pred, y)):
        print(f"Point {i+1}: {pred:0.4f} (actual: {actual})")
if __name__ == "__main__":
    main()

Optimal weights w*:
bias    : 0.0870
x1²     : 0.1522
x2²     : 0.1739
√2x1    : 0.0000
√2x2    : 0.0000
√2x1x2  : 0.0000

Predictions vs Actual:
Point 1: 0.7826 (actual: 1)
Point 2: 0.2391 (actual: 1)
Point 3: 0.7826 (actual: 1)
Point 4: 0.2391 (actual: 1)
Point 5: 0.0870 (actual: -1)


In [3]:
import numpy as np

# Define phi transformation
def phi(x):
    x_1, x_2 = x
    c = np.sqrt(2)
    return np.array([
        1,
        x_1**2,
        x_2**2,
        c * x_1,
        c * x_2,
        c * x_1 * x_2
    ])

# Training data
X = np.array([
    [0, 2],
    [1, 0],
    [0, -2],
    [-1, 0],
    [0, 0]
])
y = np.array([1, 1, 1, 1, -1])

# Get number of samples
n = len(X)

# Set regularization parameter
ell = 2

# Create feature matrix Phi
Phi = np.array([phi(x) for x in X])

# Calculate optimal parameters w
w = np.linalg.inv(Phi.T @ Phi + n * ell * np.eye(Phi.shape[1])) @ Phi.T @ y

# New point
x_new = np.array([1, 1])

# Transform new point
phi_x_new = phi(x_new)

# Calculate prediction
prediction = phi_x_new @ w

print(f"Prediction for x = (1,1): {prediction}")

Prediction for x = (1,1): 0.4130434782608696


In [ ]:
import numpy as np

# Define the data points
X = np.array([
    [0, 2],
    [1, 0],
    [0, -2],
    [-1, 0],
    [0, 0]
])

def kernel(x1, x2):
    """Compute kernel κ(x1,x2) = (1 + x1ᵀx2)²"""
    return (1 + np.dot(x1, x2))**2

# Initialize kernel matrix
n = len(X)
K = np.zeros((n, n))

# Compute each element K[i,j]
for i in range(n):
    for j in range(n):
        K[i,j] = kernel(X[i], X[j])

print("Kernel matrix K:")
print(K)
print("\nDetailed calculations:")
for i in range(n):
    for j in range(n):
        dot_product = np.dot(X[i], X[j])
        k_value = (1 + dot_product)**2
        print(f"K[{i+1},{j+1}] = (1 + ({X[i]} · {X[j]}))² = (1 + {dot_product})² = {k_value}")

Kernel matrix K:
[[25.  1.  9.  1.  1.]
 [ 1.  4.  1.  0.  1.]
 [ 9.  1. 25.  1.  1.]
 [ 1.  0.  1.  4.  1.]
 [ 1.  1.  1.  1.  1.]]

Detailed calculations:
K[1,1] = (1 + ([0 2] · [0 2]))² = (1 + 4)² = 25
K[1,2] = (1 + ([0 2] · [1 0]))² = (1 + 0)² = 1
K[1,3] = (1 + ([0 2] · [ 0 -2]))² = (1 + -4)² = 9
K[1,4] = (1 + ([0 2] · [-1  0]))² = (1 + 0)² = 1
K[1,5] = (1 + ([0 2] · [0 0]))² = (1 + 0)² = 1
K[2,1] = (1 + ([1 0] · [0 2]))² = (1 + 0)² = 1
K[2,2] = (1 + ([1 0] · [1 0]))² = (1 + 1)² = 4
K[2,3] = (1 + ([1 0] · [ 0 -2]))² = (1 + 0)² = 1
K[2,4] = (1 + ([1 0] · [-1  0]))² = (1 + -1)² = 0
K[2,5] = (1 + ([1 0] · [0 0]))² = (1 + 0)² = 1
K[3,1] = (1 + ([ 0 -2] · [0 2]))² = (1 + -4)² = 9
K[3,2] = (1 + ([ 0 -2] · [1 0]))² = (1 + 0)² = 1
K[3,3] = (1 + ([ 0 -2] · [ 0 -2]))² = (1 + 4)² = 25
K[3,4] = (1 + ([ 0 -2] · [-1  0]))² = (1 + 0)² = 1
K[3,5] = (1 + ([ 0 -2] · [0 0]))² = (1 + 0)² = 1
K[4,1] = (1 + ([-1  0] · [0 2]))² = (1 + 0)² = 1
K[4,2] = (1 + ([-1  0] · [1 0]))² = (1 + -1)² = 0
K[4,3] = (1 

In [5]:
import numpy as np

# Given kernel matrix K
K = np.array([
    [25, 1, 9, 1, 1],
    [1, 4, 1, 0, 1],
    [9, 1, 25, 1, 1],
    [1, 0, 1, 4, 1],
    [1, 1, 1, 1, 1]
])

# Target values y
y = np.array([1, 1, 1, 1, -1])

# Parameters
n = len(y)          # number of samples = 5
lambda_param = 2    # regularization parameter

# Compute (K + nλI)⁻¹y
I = np.eye(n)
alpha = np.linalg.solve(K + n * lambda_param * I, y)

print("Optimal α vector:")
print(alpha)

# Print individual α values for clarity
print("\nIndividual α values:")
for i, a in enumerate(alpha):
    print(f"α_{i+1} = {a:.6f}")

Optimal α vector:
[ 0.02173913  0.07608696  0.02173913  0.07608696 -0.10869565]

Individual α values:
α_1 = 0.021739
α_2 = 0.076087
α_3 = 0.021739
α_4 = 0.076087
α_5 = -0.108696


In [ ]:
import numpy as np

# Training points
X = np.array([
    [0, 2],    # x₁
    [1, 0],    # x₂
    [0, -2],   # x₃
    [-1, 0],   # x₄
    [0, 0]     # x₅
])

# Given kernel matrix K
K = np.array([
    [25, 1, 9, 1, 1],
    [1, 4, 1, 0, 1],
    [9, 1, 25, 1, 1],
    [1, 0, 1, 4, 1],
    [1, 1, 1, 1, 1]
])

# Target values
y = np.array([1, 1, 1, 1, -1])

# Parameters
n = len(y)  
lambda_param = 2

# Create identity matrix and compute optimal 
I = np.eye(n)  
alpha = np.linalg.solve(K + n * lambda_param * I, y)

def kernel(x1, x2):
    return (1 + np.dot(x1, x2))**2

# New point x = (1,1)ᵀ
x_new = np.array([1, 1])

# Calculate H₂(x) = Σᵢ αᵢκ(xᵢ, x)
prediction = 0
print("\nCalculating H₂(x) for x = (1,1):")
for i in range(n):
    k_i = kernel(X[i], x_new)
    term = alpha[i] * k_i
    prediction += term
    print(f"α_{i+1} * κ(x_{i+1}, x) = {alpha[i]:.6f} * {k_i:.6f} = {term:.6f}")

print(f"\nFinal prediction H₂(x) = {prediction:.6f}")


Calculating H₂(x) for x = (1,1):
α_1 * κ(x_1, x) = 0.021739 * 9.000000 = 0.195652
α_2 * κ(x_2, x) = 0.076087 * 4.000000 = 0.304348
α_3 * κ(x_3, x) = 0.021739 * 1.000000 = 0.021739
α_4 * κ(x_4, x) = 0.076087 * 0.000000 = 0.000000
α_5 * κ(x_5, x) = -0.108696 * 1.000000 = -0.108696

Final prediction H₂(x) = 0.413043


In [ ]:
import numpy as np

# Given probabilities P(Y)
P_Y0 = 0.4
P_Y1 = 0.6
# For x in [0,1]:
p0 = (1/5) * P_Y0   
p1 = (1/6) * P_Y1   
print(f"x in [0,1]:")
print(f"P(X|Y=1)P(Y=1) = {p1:.3f}")
print(f"P(X|Y=0)P(Y=0) = {p0:.3f}")
print(f"Predict y=1\n" if p1 > p0 else "Predict y=0\n")

# For x in (1,2]:
p0 = (1/5) * P_Y0
p1 = (1/8) * P_Y1
print(f"x in (1,2]:")
print(f"P(X|Y=1)P(Y=1) = {p1:.3f}")
print(f"P(X|Y=0)P(Y=0) = {p0:.3f}")
print(f"Predict y=1\n" if p1 > p0 else "Predict y=0\n")

# For x in (2,3]:
p0 = (1/3) * P_Y0
p1 = (1/8) * P_Y1
print(f"x in (2,3]:")
print(f"P(X|Y=1)P(Y=1) = {p1:.3f}")
print(f"P(X|Y=0)P(Y=0) = {p0:.3f}")
print(f"Predict y=1\n" if p1 > p0 else "Predict y=0\n")

# For x in (3,5]:
p0 = (1/15) * P_Y0
p1 = (1/8) * P_Y1
print(f"x in (3,5]:")
print(f"P(X|Y=1)P(Y=1) = {p1:.3f}")
print(f"P(X|Y=0)P(Y=0) = {p0:.3f}")
print(f"Predict y=1\n" if p1 > p0 else "Predict y=0\n")

# For x in (5,7]:
p0 = (1/15) * P_Y0
p1 = (1/6) * P_Y1
print(f"x in (5,7]:")
print(f"P(X|Y=1)P(Y=1) = {p1:.3f}")
print(f"P(X|Y=0)P(Y=0) = {p0:.3f}")
print(f"Predict y=1\n" if p1 > p0 else "Predict y=0\n")

x in [0,1]:
P(X|Y=1)P(Y=1) = 0.100
P(X|Y=0)P(Y=0) = 0.080
Predict y=1

x in (1,2]:
P(X|Y=1)P(Y=1) = 0.075
P(X|Y=0)P(Y=0) = 0.080
Predict y=0

x in (2,3]:
P(X|Y=1)P(Y=1) = 0.075
P(X|Y=0)P(Y=0) = 0.133
Predict y=0

x in (3,5]:
P(X|Y=1)P(Y=1) = 0.075
P(X|Y=0)P(Y=0) = 0.027
Predict y=1

x in (5,7]:
P(X|Y=1)P(Y=1) = 0.100
P(X|Y=0)P(Y=0) = 0.027
Predict y=1



the Bayes classifier predicts y=1 for x in [0,1] ∪ (3,7]

In [8]:
import numpy as np

# Parameters
mu1, sigma1 = 2, 3  # Y=1 Gaussian parameters
mu0, sigma0 = 5, 3  # Y=0 Gaussian parameters
P_Y1 = 0.5         # Prior P(Y=1)
P_Y0 = 0.5         # Prior P(Y=0)

def gaussian_pdf(x, mu, sigma):
    """Calculate Gaussian probability density at x"""
    return (1/(sigma*np.sqrt(2*np.pi))) * np.exp(-(x-mu)**2/(2*sigma**2))

# Since σ₁=σ₀ and P(Y=1)=P(Y=0), the decision boundary is at the midpoint
x_boundary = (mu0 + mu1)/2  # = 3.5

# To compute the Bayes error, we need to integrate the error regions
# We'll use numerical integration (trapezoidal rule)
def trapz_integrate(f, a, b, n=1000):
    """Integrate function f from a to b using trapezoidal rule"""
    x = np.linspace(a, b, n)
    y = f(x)
    return np.trapz(y, x)

# Error for Y=1 class (integrate beyond boundary)
def error_integrand_y1(x):
    return gaussian_pdf(x, mu1, sigma1) * P_Y1

error_y1 = trapz_integrate(error_integrand_y1, x_boundary, mu1 + 4*sigma1)

# Error for Y=0 class (integrate before boundary)
def error_integrand_y0(x):
    return gaussian_pdf(x, mu0, sigma0) * P_Y0

error_y0 = trapz_integrate(error_integrand_y0, mu0 - 4*sigma0, x_boundary)

total_error = error_y1 + error_y0

print(f"Decision boundary: x = {x_boundary}")
print(f"Bayes error ≈ {total_error:.4f}")
print(f"Contributions:")
print(f"From Y=1 class: {error_y1:.4f}")
print(f"From Y=0 class: {error_y0:.4f}")

Decision boundary: x = 3.5
Bayes error ≈ 0.3085
Contributions:
From Y=1 class: 0.1543
From Y=0 class: 0.1543


C:\Users\jacki\AppData\Local\Temp\ipykernel_38276\157006244.py:22: DeprecationWarning: `trapz` is deprecated. Use `trapezoid` instead, or one of the numerical integration functions in `scipy.integrate`.
  return np.trapz(y, x)
